sudo: false
language: "ruby"
rvm:
  - "1.9.3"
  - "2.2.4"
  - "2.4"
  # - "2.5" https://github.com/apiaryio/dredd-hooks-ruby/issues/36
  - "2.6"
before_install:
  - "nvm install node && nvm use node"
  - "npm install"
script:
  - "export BUNDLE_GEMFILE=$(pwd)/Gemfile"
  - "bundle exec rake && npm test"
